
package Library_Presentation;

//import  My_Forms.Authors_list_Form1.jTable_Authors;
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

/**
 *
 * @author omayma
 */
  
public class AddBookForm extends javax.swing.JFrame {
   
    Library_Domain.Member member = new Library_Domain.Member();
    Library_Business.Function_Class func= new Library_Business.Function_Class();
    Library_Domain.Genre genre= new Library_Domain.Genre();
    HashMap<String, Integer> genreMap = genre.getGHashMap();
    String imagePath = " ";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddBookForm.class.getName());
    
    /**
     * Creates new form Member_List_info
     */
    public AddBookForm() {
          initComponents();
        // center form
        this.setLocationRelativeTo(null);
        
        // add borderto the panel Header                                      
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 5, 3, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
          try {
         java.net.URL imaUrl = getClass().getResource("/My_Images/bookbook.png");
             if (imaUrl != null) {
        // هذا السطر ينظف المسار من أي تشفير أو رموز زائدة لتقرأه الدالة بسلام
        String cleanPath = java.nio.file.Paths.get(imaUrl.toURI()).toFile().getAbsolutePath();
        
        func.displayImage(90, 60, null, cleanPath,  jLabel1);
    }
         } catch (Exception e) {
               e.printStackTrace();
                   }
         fillJcocomboboxWhidthGeneres();
         //populate Jcombobox genres
      
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2_Image = new javax.swing.JPanel();
        jTextField_Id1 = new javax.swing.JTextField();
        jTextField_Genre = new javax.swing.JTextField();
        jTextField_recived_data = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Quantity = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Author = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_ISBN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Price_ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Publisher = new javax.swing.JTextField();
        jLabel1_Genre_ID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_Description = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel_image_ = new javax.swing.JLabel();
        jLabel_ImagePhoto = new javax.swing.JLabel();
        jButton_AddBookCover = new javax.swing.JButton();
        jButton_AddNewBook = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jComboBox_Genre = new javax.swing.JComboBox<>();
        jCalendarComboBox_Date = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel17 = new javax.swing.JLabel();
        jSpinner_Quantity = new javax.swing.JSpinner();
        jButton_select_author = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1_Author_ID = new javax.swing.JLabel();
        jButton_Clear = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2_ImageLayout = new javax.swing.GroupLayout(jPanel2_Image);
        jPanel2_Image.setLayout(jPanel2_ImageLayout);
        jPanel2_ImageLayout.setHorizontalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2_ImageLayout.setVerticalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jTextField_Id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Id1.addActionListener(this::jTextField_Id1ActionPerformed);

        jTextField_Genre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Genre.addActionListener(this::jTextField_GenreActionPerformed);

        jTextField_recived_data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_recived_data.addActionListener(this::jTextField_recived_dataActionPerformed);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setText("Recived Date :");

        jTextField_Quantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Quantity.addActionListener(this::jTextField_QuantityActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 570));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1103, 573));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1103, 573));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(86, 80));
        jLabel2.setMinimumSize(new java.awt.Dimension(86, 80));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(1, 152, 117));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("إضافة كتاب جديد ");
        jLabel1.setMaximumSize(new java.awt.Dimension(684, 32));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(684, 32));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setText("     ISBN:");

        jTextField_Author.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Author.addActionListener(this::jTextField_AuthorActionPerformed);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setText(" أسم الكتاب    ");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("الكمية ");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel10.setText("المؤلف   ");

        jTextField_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Name.addActionListener(this::jTextField_NameActionPerformed);

        jTextField_ISBN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_ISBN.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_ISBN.addActionListener(this::jTextField_ISBNActionPerformed);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel11.setText("تاريخ الاستلام");

        jTextField_Price_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Price_.addActionListener(this::jTextField_Price_ActionPerformed);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setText("السعر");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel14.setText("النوع ");

        jTextField_Publisher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Publisher.addActionListener(this::jTextField_PublisherActionPerformed);

        jLabel1_Genre_ID.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1_Genre_ID.setText("ID");

        jTextArea1_Description.setColumns(20);
        jTextArea1_Description.setRows(5);
        jTextArea1_Description.setMaximumSize(new java.awt.Dimension(264, 118));
        jTextArea1_Description.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane1.setViewportView(jTextArea1_Description);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel16.setText("الوصف : ");

        jLabel_image_.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_image_.setOpaque(true);
        jLabel_image_.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel_image_AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_ImagePhoto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_ImagePhoto.setForeground(new java.awt.Color(51, 0, 255));
        jLabel_ImagePhoto.setText("مسار الصورة ..");
        jLabel_ImagePhoto.setMaximumSize(new java.awt.Dimension(31, 31));
        jLabel_ImagePhoto.setMinimumSize(new java.awt.Dimension(286, 31));

        jButton_AddBookCover.setText("اختيار صورة الغلاف ");
        jButton_AddBookCover.setMaximumSize(new java.awt.Dimension(140, 31));
        jButton_AddBookCover.setMinimumSize(new java.awt.Dimension(110, 23));
        jButton_AddBookCover.addActionListener(this::jButton_AddBookCoverActionPerformed);

        jButton_AddNewBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_AddNewBook.setText("إضافة");
        jButton_AddNewBook.addActionListener(this::jButton_AddNewBookActionPerformed);

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Cancel.setText("إلغاء ");
        jButton_Cancel.addActionListener(this::jButton_CancelActionPerformed);

        jComboBox_Genre.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBox_Genre.addActionListener(this::jComboBox_GenreActionPerformed);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel17.setText("الناشر ");

        jSpinner_Quantity.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton_select_author.setText("أختيار مؤلف ");
        jButton_select_author.addActionListener(this::jButton_select_authorActionPerformed);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel18.setText("صورة الغلاف ");

        jLabel1_Author_ID.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1_Author_ID.setText("ID");

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Clear.setText("مسح الحقول ");
        jButton_Clear.addActionListener(this::jButton_ClearActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_AddBookCover, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_ImagePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_image_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(200, 200, 200)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_AddNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1_Genre_ID)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSpinner_Quantity)
                                        .addComponent(jTextField_Price_)
                                        .addComponent(jTextField_Publisher)
                                        .addComponent(jCalendarComboBox_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jButton_select_author, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1_Author_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_Author, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                        .addComponent(jTextField_Name))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(445, 445, 445))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_select_author)
                                    .addComponent(jLabel1_Author_ID)
                                    .addComponent(jTextField_Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_Genre_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Price_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCalendarComboBox_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addComponent(jLabel_ImagePhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_image_, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton_AddBookCover, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButton_AddNewBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Cancel))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //close form
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AuthorActionPerformed
        
        
    }//GEN-LAST:event_jTextField_AuthorActionPerformed

    private void jTextField_Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Id1ActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ISBNActionPerformed

    private void jTextField_GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenreActionPerformed

    private void jTextField_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_QuantityActionPerformed

    private void jTextField_recived_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_recived_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_recived_dataActionPerformed

    private void jTextField_Price_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Price_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Price_ActionPerformed

    private void jTextField_PublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PublisherActionPerformed

    private void jButton_AddBookCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddBookCoverActionPerformed
                    
                String path = func.selectImage();
                jLabel_ImagePhoto.setText(path);
                // imagePath = path;
                 func.displayImage(140, 150, null,path, jLabel_image_);
                 imagePath = path;
            
        
        
    
    }//GEN-LAST:event_jButton_AddBookCoverActionPerformed

    private void jButton_AddNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddNewBookActionPerformed
    
    System.out.println("BUTTON CLICKED");

    Library_Domain.Book book = new Library_Domain.Book();
    String isbn = jTextField_ISBN.getText();

    // 🔴 التحقق من الحقول الأساسية
    if(!verif()){
        JOptionPane.showMessageDialog(
            null,
            "الرقم الدولي ISBN,او اسم الكتاب , المؤلف اوالتصنيف مطلوبة ولايمكن تركها فارغ ",
            "بيانات ناقصة",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 🔴 التحقق من ISBN
    if(book.isISBNexists(isbn)){
        JOptionPane.showMessageDialog(null,
            "الرقم الدولي  ISBN مسجل مسبقاً ",
            "خطأ !",
            0);
        return;
    }

    // 🔴 التحقق من الصورة (إجباري)
    if(imagePath == null || imagePath.trim().isEmpty()){
        JOptionPane.showMessageDialog(null,
            "ادخل صورة الغلاف للكتاب رجاءً",
            "نسيت الصورة ",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try{

        String name = jTextField_Name.getText();
        String publisher = jTextField_Publisher.getText();
        String description = jTextArea1_Description.getText();

        Integer auther_id = Integer.parseInt(jLabel1_Author_ID.getText());
        Integer genre_id = Integer.parseInt(jLabel1_Genre_ID.getText());
        Integer quantity = Integer.parseInt(jSpinner_Quantity.getValue().toString());
        double price = Double.parseDouble(jTextField_Price_.getText());

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String received_date = dateFormat.format(jCalendarComboBox_Date.getDate());

        Path path = Paths.get(imagePath);
        byte[] img = Files.readAllBytes(path);

        book.addBook(isbn, name, auther_id, genre_id, quantity,
                publisher, received_date, price, description, img);

    }
    catch(IOException ex){
        JOptionPane.showMessageDialog(null,
            "تحميل ملف الصورة ",
            "لايوجد غلاف ",
            0);
        System.out.println("IOException");
    }
    catch(NumberFormatException ex){
        JOptionPane.showMessageDialog(null,
            "خطأ في ادخال الارقام ",
            "خطأ",
            0);
        System.out.println("NumberFormatException");
    }
    catch(NullPointerException ex){
        JOptionPane.showMessageDialog(null,
            "اختار التاريخ ",
            "التاريخ ! ",
            0);
        System.out.println("NullPointerException");
    }


       
    }//GEN-LAST:event_jButton_AddNewBookActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        
        // close windo 
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jLabel_image_AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel_image_AncestorAdded
        
    }//GEN-LAST:event_jLabel_image_AncestorAdded

    private void jButton_select_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_select_authorActionPerformed
        Authors_list_Form1 form = new Authors_list_Form1();
         form.setAddBookForm(this);
         form.setVisible(true);
        
     
        
    }//GEN-LAST:event_jButton_select_authorActionPerformed

    private void jComboBox_GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_GenreActionPerformed
        // Display the selected genre : 
        try{
        int genreId = genreMap.get(jComboBox_Genre.getSelectedItem().toString());
        jLabel1_Genre_ID.setText(String.valueOf(genreId));
        }catch(Exception ex){
            System.err.println("خطأ في الوصول لنوع الكتاب "+ ex.getMessage());
        
        }
    }//GEN-LAST:event_jComboBox_GenreActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
         jTextField_ISBN.setText(" ");
         jTextField_Name.setText(" ");
         jTextField_Publisher.setText("");
         jTextArea1_Description.setText("");
         jLabel1_Author_ID.setText("");
         jLabel1_Genre_ID.setText("");
         jSpinner_Quantity.setValue(0);
         jTextField_Price_.setText("");
         jTextArea1_Description.setText("");
         jCalendarComboBox_Date.setDate(new java.util.Date());
         jLabel_image_.setIcon(null);
         jTextField_Author.setText("");
         jLabel_ImagePhoto.setText("");
         
    }//GEN-LAST:event_jButton_ClearActionPerformed

   public void displayAuthorData(int id, String fullName) {
    jTextField_Author.setText(fullName);
    jLabel1_Author_ID.setText(String.valueOf(id));
}
    //=======================================================================
private boolean verif() {

    if(jTextField_ISBN.getText().trim().isEmpty()
    || jTextField_Name.getText().trim().isEmpty()
    || jLabel1_Author_ID.getText().trim().isEmpty()
    || jLabel1_Genre_ID.getText().trim().isEmpty())
    {
        return false;
    }

    return true;
}
 //==========================================================================
 
    public void fillJcocomboboxWhidthGeneres()
    {
    for(String genreName : genreMap.keySet())
    {
    jComboBox_Genre.addItem(genreName);
    }
    
    }    // create function to populate the table with Author
  public void populatJtablewithMember(String query) {
    try {
        // جلب قائمة الأعضاء من قاعدة البيانات داخل الـ try لحمايتها
        ArrayList<Library_Domain.Member> membersList = member.membersList(query);
        
        // أعمدة الجدول
        String[] colNames = {"ID", "F-NAME", "L-NAME", "PHONE", "EMAIL", "GENDER"};
        
        // الأسطر 
        Object[][] rows = new Object[membersList.size()][colNames.length];
        for (int i = 0; i < membersList.size(); i++) {
            rows[i][0] = membersList.get(i).getId();
            rows[i][1] = membersList.get(i).getFirstName();
            rows[i][2] = membersList.get(i).getLastName();
            rows[i][3] = membersList.get(i).getPhone();
            rows[i][4] = membersList.get(i).getEmail();
            rows[i][5] = membersList.get(i).getGender();
        }
        
       /* DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Members_.setModel(model); */
        
    } catch (java.sql.SQLException ex) {
        // في حال حدوث خطأ في قاعدة البيانات، يتم عرض رسالة تنبيه للمستخدم
        javax.swing.JOptionPane.showMessageDialog(null, "Error populating table: " + ex.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddBookForm().setVisible(true));
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddBookCover;
    private javax.swing.JButton jButton_AddNewBook;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_select_author;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox_Date;
    private javax.swing.JComboBox<String> jComboBox_Genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private static javax.swing.JLabel jLabel1_Author_ID;
    private javax.swing.JLabel jLabel1_Genre_ID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_ImagePhoto;
    private javax.swing.JLabel jLabel_image_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_Image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_Quantity;
    private javax.swing.JTextArea jTextArea1_Description;
    private static javax.swing.JTextField jTextField_Author;
    private javax.swing.JTextField jTextField_Genre;
    private javax.swing.JTextField jTextField_ISBN;
    private javax.swing.JTextField jTextField_Id1;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Price_;
    private javax.swing.JTextField jTextField_Publisher;
    private javax.swing.JTextField jTextField_Quantity;
    private javax.swing.JTextField jTextField_recived_data;
    // End of variables declaration//GEN-END:variables


}
