
package Library_Presentation;
import Library_Data.DB;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author omayma
 */
  
public class Book_List_info1 extends javax.swing.JFrame {
    Library_Domain.Book book = new Library_Domain.Book();
    Library_Business.Function_Class func= new Library_Business.Function_Class();
    Library_Domain.Authors authors = new Library_Domain.Authors();
    Library_Domain.Genre genre = new Library_Domain.Genre();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Book_List_info1.class.getName());

    /**
     * Creates new form Member_List_info
     */
    public Book_List_info1() {
          initComponents();
        // center form
        this.setLocationRelativeTo(null);
        
        // add borderto the panel Header                                      
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 5, 3, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
      
          Library_Business.Function_Class func = new Library_Business.Function_Class();
 try {
         java.net.URL imaUrl = getClass().getResource("/My_Images/bookbook.png");
             if (imaUrl != null) {
        String cleanPath = java.nio.file.Paths.get(imaUrl.toURI()).toFile().getAbsolutePath();
        
        func.displayImage(90, 60, null, cleanPath,  jLabel1);
    }
         } catch (Exception e) {
               e.printStackTrace();
                   }
         
        Library_Business.BaseUI_Service buis = new Library_Business.BaseUI_Service();
        // customize table
        buis.customizeTable(jTable_Books_,new Color(3,152,117),Color.white);

        // to hide thered sentence 
      populatJtablewithBook("SELECT * FROM books");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2_Image = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Books_ = new javax.swing.JTable();
        jLabel_ISBM = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_euthor = new javax.swing.JLabel();
        jLabel_genre = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jLabel_publisher = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_book_search_ = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCalendarComboBox_2 = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCalendarComboBox_1 = new de.wannawork.jcalendar.JCalendarComboBox();
        jButton_search_betweenTwoDate = new javax.swing.JButton();
        jLabel_image = new javax.swing.JLabel();
        jButton_report = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2_ImageLayout = new javax.swing.GroupLayout(jPanel2_Image);
        jPanel2_Image.setLayout(jPanel2_ImageLayout);
        jPanel2_ImageLayout.setHorizontalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2_ImageLayout.setVerticalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(1, 152, 117));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("قائمة الكتب ");
        jLabel1.setOpaque(true);

        jTable_Books_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Books_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Books_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Books_);

        jLabel_ISBM.setText("ISBN");

        jLabel_name.setText("الاسم");

        jLabel_euthor.setText("المؤلف");

        jLabel_genre.setText("الصنف");

        jLabel_price.setText("السعر");

        jLabel_publisher.setText("دار النشر");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("أبحث هنا ");

        jTextField_book_search_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_book_search_.addActionListener(this::jTextField_book_search_ActionPerformed);

        jButton_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_search.setText("بحث");
        jButton_search.addActionListener(this::jButton_searchActionPerformed);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*يتم البحث بواسطة اسم الكتاب ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_book_search_, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_book_search_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_search))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setText("تاريخ الاستلام من ");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("* بحث بين التاريخين ");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("حتى");

        jButton_search_betweenTwoDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_search_betweenTwoDate.setText("بحث");
        jButton_search_betweenTwoDate.addActionListener(this::jButton_search_betweenTwoDateActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendarComboBox_1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendarComboBox_2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_search_betweenTwoDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_search_betweenTwoDate)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendarComboBox_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendarComboBox_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel_image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_image.setOpaque(true);

        jButton_report.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_report.setText("تقرير");
        jButton_report.addActionListener(this::jButton_reportActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_price)
                                    .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_publisher)
                                    .addComponent(jLabel_genre)
                                    .addComponent(jLabel_euthor)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_ISBM)
                                        .addComponent(jLabel_name))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton_report, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(188, 188, 188)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_ISBM, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_euthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_publisher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_price, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_report)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //close form
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    
   
    private void jTextField_book_search_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_book_search_ActionPerformed
   // search & display data in table 
        String value = jTextField_book_search_.getText();
        String query ="SELECT * FROM books WHERE `name` LIKE '%" + value +"%'";
        populatJtablewithBook(query);
    }//GEN-LAST:event_jTextField_book_search_ActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        // search & display data in table 
        String value = jTextField_book_search_.getText();
        String query ="SELECT * FROM books WHERE `name` LIKE '%" + value +"%'";
        populatJtablewithBook(query);
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jTable_Books_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Books_MouseClicked
                                           
    Library_Domain.Book selectBook = null;
    try {
        // 1. الحصول على الصف المحدد
        int rowIndex = jTable_Books_.getSelectedRow();
        if (rowIndex == -1) return; 

        // 2. البحث عن رقم عمود الـ ID ديناميكياً باستخدام اسمه
        int idColumnIndex = -1;
        for (int i = 0; i < jTable_Books_.getColumnCount(); i++) {
            if (jTable_Books_.getColumnName(i).equalsIgnoreCase("ID")) {
                idColumnIndex = i;
                break;
            }
        }

        // إذا لم يجد عمود باسم ID، نستخدم العمود رقم 0 كخيار احتياطي طوارئ
        if (idColumnIndex == -1) {
            idColumnIndex = 0; 
        }

        // 3. جلب القيمة وتحويلها إلى رقم ID صريح
        Object idValue = jTable_Books_.getValueAt(rowIndex, idColumnIndex); 
        if (idValue == null) {
            JOptionPane.showMessageDialog(this, "خطأ: خانة المعرّف ID فارغة في هذا الصف.");
            return;
        }
        
        int id = Integer.parseInt(idValue.toString().trim());

        // 4. استدعاء بيانات الكتاب من قاعدة البيانات
        selectBook = book.getBookByID(id);

        if (selectBook != null) {
            // تعبئة النصوص في الشاشة
            jLabel_ISBM.setText(selectBook.getIsbn());
            jLabel_name.setText(selectBook.getName());
            
            // عرض اسم المؤلف بأمان
            if (authors != null && authors.getAuthorsByID(selectBook.getAuthor_id()) != null) {
                jLabel_euthor.setText(authors.getAuthorsByID(selectBook.getAuthor_id()).getFirstName() + " " + authors.getAuthorsByID(selectBook.getAuthor_id()).getLastName());
            } else {
                jLabel_euthor.setText(String.valueOf(selectBook.getAuthor_id()));
            }
            
            // عرض التصنيف بأمان
            if (genre != null && genre.getGenreByID(selectBook.getGenre_id()) != null) {
                jLabel_genre.setText(genre.getGenreByID(selectBook.getGenre_id()).getName());
            } else {
                jLabel_genre.setText(String.valueOf(selectBook.getGenre_id()));
            }
            
            jLabel_publisher.setText(selectBook.getPublisher());
            jLabel_price.setText(String.valueOf(selectBook.getPrice()));

            // 5. عرض الصورة
            byte[] image = selectBook.getCover();
            if (image != null && image.length > 0) {
                func.displayImage(jLabel_image.getWidth(), jLabel_image.getHeight(), image, "", jLabel_image);
            } else {
                jLabel_image.setIcon(null); 
            }

        } else {
            JOptionPane.showMessageDialog(null, "عفواً، لم يتم العثور على بيانات هذا الكتاب بالـ ID: " + id, "خطأ", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jTable_Books_MouseClicked

    private void jButton_search_betweenTwoDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_betweenTwoDateActionPerformed
       // search by  two Date & display data in table 
        try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = dateFormat.format(jCalendarComboBox_1.getDate());
        String date2 = dateFormat.format(jCalendarComboBox_2.getDate());
        String query ="SELECT * FROM books WHERE date_revived BETWEEN '"+date1+"' AND '"+date2+"'";
        populatJtablewithBook(query);
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"اختار التاريخين قبل البحث ","مشكلة!",0);
        }
       
    }//GEN-LAST:event_jButton_search_betweenTwoDateActionPerformed

    private void jButton_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reportActionPerformed
       try {
    // 1. تحديد مسار التقرير داخل الـ resources
    java.io.InputStream reportStream = getClass().getResourceAsStream("/books_report.jasper");
    
    if (reportStream == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "لم يتم العثور على ملف التقرير!");
        return;
    }

    // 2. باراميترز فارغة (لو مش مستخدمتيهم)
    java.util.HashMap<String, Object> parameters = new java.util.HashMap<>();
    
    // 3. تعبئة التقرير بالبيانات عبر استدعاء اتصال قاعدة البيانات الخاص بكِ
    net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportStream, parameters, DB.getConnection());

    // 4. عرض التقرير في نافذة للمستخدم
    net.sf.jasperreports.view.JasperViewer viewer = new net.sf.jasperreports.view.JasperViewer(jasperPrint, false);
    viewer.setTitle("قائمة الكتب");
    viewer.setVisible(true);

} catch (Exception e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "خطأ أثناء عرض التقرير: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton_reportActionPerformed

        //==========================================
  // create function to populate the table with Author
  public void populatJtablewithBook(String query) {
      // جلب قائمة الأعضاء من قاعدة البيانات داخل الـ try لحمايتها
        ArrayList<Library_Domain.Book> booksList = book.booksList(query);
        
        // أعمدة الجدول
        String[] colNames = {  "الكمية","دار النشر ","السعر","تاريخ الاستلام" ,"الصنف","المؤلف","عنوان الكتاب", "ISBN","ID"};
        
        // الأسطر 
        Object[][] rows = new Object[booksList.size()][colNames.length];
        for (int i = 0; i < booksList.size(); i++) {
            rows[i][8] = booksList.get(i).getId();
            rows[i][7] = booksList.get(i).getIsbn();
            rows[i][6] = booksList.get(i).getName();
            rows[i][5] = booksList.get(i).getAuthor_id();
            rows[i][4] = booksList.get(i).getGenre_id();
            rows[i][0] = booksList.get(i).getQuantity();
            rows[i][1] = booksList.get(i).getPublisher();
            rows[i][2] = booksList.get(i).getPrice();
            rows[i][3] = booksList.get(i).getDate_revived();
            
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Books_.setModel(model);
        }    
//======================================================
    /**
     * @param args the command line arguments
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Book_List_info1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_report;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_search_betweenTwoDate;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox_1;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_ISBM;
    private javax.swing.JLabel jLabel_euthor;
    private javax.swing.JLabel jLabel_genre;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JLabel jLabel_publisher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_Image;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Books_;
    private javax.swing.JTextField jTextField_book_search_;
    // End of variables declaration//GEN-END:variables
}
