
package Library_Presentation;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

/**
 *
 * @author omayma
 */
  
public class DeleteBookForm1 extends javax.swing.JFrame {
   
    Library_Domain.Member member = new Library_Domain.Member();
    Library_Business.Function_Class func= new Library_Business.Function_Class();
    Library_Domain.Genre genre= new Library_Domain.Genre();
    HashMap<String, Integer> genreMap = genre.getGHashMap();
    String imagePath = " ";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteBookForm1.class.getName());
    
    /**
     * Creates new form Member_List_info
     */
    public DeleteBookForm1() {
          initComponents();
        // center form
        this.setLocationRelativeTo(null);
        
        // add borderto the panel Header                                      
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 5, 3, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
        
         try {
         java.net.URL imaUrl = getClass().getResource("/My_Images/bookbook.png");
             if (imaUrl != null) {
        // هذا السطر ينظف المسار من أي تشفير أو رموز زائدة لتقرأه الدالة بسلام
        String cleanPath = java.nio.file.Paths.get(imaUrl.toURI()).toFile().getAbsolutePath();
        
        func.displayImage(90, 60, null, cleanPath,  jLabel1);
    }
         } catch (Exception e) {
               e.printStackTrace();
                   }
         //fillJcocomboboxWhidthGeneres();
         //populate Jcombobox genres
      
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2_Image = new javax.swing.JPanel();
        jTextField_Id1 = new javax.swing.JTextField();
        jTextField_Genre = new javax.swing.JTextField();
        jTextField_recived_data = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Quantity = new javax.swing.JTextField();
        jTextField_Remove_ = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_RemoveBook = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jSpinner1_remove = new javax.swing.JSpinner();

        javax.swing.GroupLayout jPanel2_ImageLayout = new javax.swing.GroupLayout(jPanel2_Image);
        jPanel2_Image.setLayout(jPanel2_ImageLayout);
        jPanel2_ImageLayout.setHorizontalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2_ImageLayout.setVerticalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jTextField_Id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Id1.addActionListener(this::jTextField_Id1ActionPerformed);

        jTextField_Genre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Genre.addActionListener(this::jTextField_GenreActionPerformed);

        jTextField_recived_data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_recived_data.addActionListener(this::jTextField_recived_dataActionPerformed);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setText("Recived Date :");

        jTextField_Quantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Quantity.addActionListener(this::jTextField_QuantityActionPerformed);

        jTextField_Remove_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Remove_.addActionListener(this::jTextField_Remove_ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(462, 217));
        jPanel1.setMinimumSize(new java.awt.Dimension(460, 210));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(86, 80));
        jLabel2.setMinimumSize(new java.awt.Dimension(86, 80));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(1, 152, 117));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Remove Book");
        jLabel1.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setText("Enter Book ID");

        jButton_RemoveBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_RemoveBook.setText("Delete");
        jButton_RemoveBook.addActionListener(this::jButton_RemoveBookActionPerformed);

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(this::jButton_CancelActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addGap(30, 30, 30)
                            .addComponent(jSpinner1_remove))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jButton_RemoveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel)
                    .addComponent(jButton_RemoveBook))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //close form
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField_Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Id1ActionPerformed

    private void jTextField_Remove_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Remove_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Remove_ActionPerformed

    private void jTextField_GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenreActionPerformed

    private void jTextField_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_QuantityActionPerformed

    private void jTextField_recived_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_recived_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_recived_dataActionPerformed

    private void jButton_RemoveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveBookActionPerformed
         Library_Domain.Book book = new Library_Domain.Book();
         Integer id = (Integer) jSpinner1_remove.getValue();
         try {
             int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure Want To Delete This Book !","confirmation Bow",JOptionPane.YES_OPTION);
                if(confirm == JOptionPane.YES_OPTION){
                  book.deleteBook(id);
                }
             } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Delete Wrong",0);
        }   
    }//GEN-LAST:event_jButton_RemoveBookActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        
        // close windo 
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed
   //=======================================================================

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeleteBookForm1().setVisible(true));
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_RemoveBook;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_Image;
    private javax.swing.JSpinner jSpinner1_remove;
    private javax.swing.JTextField jTextField_Genre;
    private javax.swing.JTextField jTextField_Id1;
    private javax.swing.JTextField jTextField_Quantity;
    private javax.swing.JTextField jTextField_Remove_;
    private javax.swing.JTextField jTextField_recived_data;
    // End of variables declaration//GEN-END:variables


}
