
package Library_Presentation;

//import  My_Forms.Authors_list_Form1.jTable_Authors;
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

/**
 *
 * @author omayma
 */
  
public class EditBookForm1 extends javax.swing.JFrame {
    Library_Domain.Member member = new Library_Domain.Member();
    Library_Domain.Book book = new Library_Domain.Book();
    Library_Business.Function_Class func= new Library_Business.Function_Class();
    Library_Domain.Genre genre= new Library_Domain.Genre();
    Library_Domain.Authors authors = new Library_Domain.Authors();
    HashMap<String, Integer> genreMap = genre.getGHashMap();
    String imagePath = " ";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditBookForm1.class.getName());
     public int selectedAuthorId;
    /**
     * Creates new form Member_List_info
     */
    public EditBookForm1() {
          initComponents();
        
        // center form
        this.setLocationRelativeTo(null);
        
        // add borderto the panel Header                                      
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 5, 3, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
        
         try {
         java.net.URL imaUrl = getClass().getResource("/My_Images/bookbook.png");
             if (imaUrl != null) {
        // هذا السطر ينظف المسار من أي تشفير أو رموز زائدة لتقرأه الدالة بسلام
        String cleanPath = java.nio.file.Paths.get(imaUrl.toURI()).toFile().getAbsolutePath();
        
        func.displayImage(90, 60, null, cleanPath,  jLabel1);
    }
         } catch (Exception e) {
               e.printStackTrace();
                   }
        // fillJcocomboboxWhidthGeneres();
         //populate Jcombobox genres
      loadGenres();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2_Image = new javax.swing.JPanel();
        jTextField_Id1 = new javax.swing.JTextField();
        jTextField_Genre = new javax.swing.JTextField();
        jTextField_recived_data = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Quantity = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Author = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_ISBN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Price_ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Publisher = new javax.swing.JTextField();
        jLabel1_Genre_ID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_Description = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel_image_ = new javax.swing.JLabel();
        jLabel_ImagePhoto = new javax.swing.JLabel();
        jButton_AddBookCover = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jComboBox_Genre = new javax.swing.JComboBox<>();
        jCalendarComboBox_Date = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel17 = new javax.swing.JLabel();
        jSpinner_Quantity = new javax.swing.JSpinner();
        jButton_s = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1_Author_ID = new javax.swing.JLabel();
        jButton_Clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jButton_Search_ = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2_ImageLayout = new javax.swing.GroupLayout(jPanel2_Image);
        jPanel2_Image.setLayout(jPanel2_ImageLayout);
        jPanel2_ImageLayout.setHorizontalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2_ImageLayout.setVerticalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jTextField_Id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Id1.addActionListener(this::jTextField_Id1ActionPerformed);

        jTextField_Genre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Genre.addActionListener(this::jTextField_GenreActionPerformed);

        jTextField_recived_data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_recived_data.addActionListener(this::jTextField_recived_dataActionPerformed);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setText("Recived Date :");

        jTextField_Quantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Quantity.addActionListener(this::jTextField_QuantityActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(777, 573));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(86, 80));
        jLabel2.setMinimumSize(new java.awt.Dimension(86, 80));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(1, 152, 117));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Book");
        jLabel1.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setText("ISBN:");

        jTextField_Author.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Author.addActionListener(this::jTextField_AuthorActionPerformed);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel6.setText("Quantity:");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel10.setText("Author:");

        jTextField_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Name.addActionListener(this::jTextField_NameActionPerformed);

        jTextField_ISBN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_ISBN.addActionListener(this::jTextField_ISBNActionPerformed);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel11.setText("Received Date:");

        jTextField_Price_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Price_.addActionListener(this::jTextField_Price_ActionPerformed);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel13.setText("Price:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel14.setText("Genre:");

        jTextField_Publisher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Publisher.addActionListener(this::jTextField_PublisherActionPerformed);

        jLabel1_Genre_ID.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1_Genre_ID.setText("ID");

        jTextArea1_Description.setColumns(20);
        jTextArea1_Description.setRows(5);
        jTextArea1_Description.setMaximumSize(new java.awt.Dimension(264, 118));
        jTextArea1_Description.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane1.setViewportView(jTextArea1_Description);

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel16.setText("Book description :");

        jLabel_image_.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_image_.setOpaque(true);
        jLabel_image_.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel_image_AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_ImagePhoto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel_ImagePhoto.setForeground(new java.awt.Color(51, 0, 255));
        jLabel_ImagePhoto.setText("  Picture Path ....");
        jLabel_ImagePhoto.setMaximumSize(new java.awt.Dimension(31, 31));
        jLabel_ImagePhoto.setMinimumSize(new java.awt.Dimension(286, 31));

        jButton_AddBookCover.setText("Select  Book Cover:");
        jButton_AddBookCover.setMaximumSize(new java.awt.Dimension(140, 31));
        jButton_AddBookCover.setMinimumSize(new java.awt.Dimension(110, 23));
        jButton_AddBookCover.addActionListener(this::jButton_AddBookCoverActionPerformed);

        jButton_Edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(this::jButton_EditActionPerformed);

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(this::jButton_CancelActionPerformed);

        jComboBox_Genre.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBox_Genre.addActionListener(this::jComboBox_GenreActionPerformed);

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel17.setText("Publisher:");

        jSpinner_Quantity.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton_s.setText("change Author");
        jButton_s.addActionListener(this::jButton_sActionPerformed);

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel18.setText("Book Cover :");

        jLabel1_Author_ID.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1_Author_ID.setText("ID");

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(this::jButton_ClearActionPerformed);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel7.setText("ID:");

        jTextField_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_ID.addActionListener(this::jTextField_IDActionPerformed);

        jButton_Search_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Search_.setText("Search by ID or ISBN");
        jButton_Search_.addActionListener(this::jButton_Search_ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCalendarComboBox_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBox_Genre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1_Genre_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField_Name)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField_Author)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1_Author_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton_s))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextField_ISBN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                                    .addComponent(jTextField_ID, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton_Search_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSpinner_Quantity)
                                            .addComponent(jTextField_Price_)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_Publisher)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton_AddBookCover, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_image_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_ImagePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_ImagePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_image_, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButton_Search_, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_s, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_Author_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_Genre_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_Price_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_AddBookCover, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCalendarComboBox_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Clear)
                        .addComponent(jButton_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Id1ActionPerformed

    private void jTextField_GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenreActionPerformed

    private void jTextField_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_QuantityActionPerformed

    private void jTextField_recived_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_recived_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_recived_dataActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        jTextField_ID.setText(" ");
        jTextField_ISBN.setText(" ");
        jTextField_Name.setText(" ");
        jTextField_Publisher.setText("");
        jTextArea1_Description.setText("");
        jLabel1_Author_ID.setText("");
        jLabel1_Genre_ID.setText("");
        jSpinner_Quantity.setValue(0);
        jTextField_Price_.setText("");
        jTextArea1_Description.setText("");
        jCalendarComboBox_Date.setDate(new java.util.Date());
        jLabel_image_.setIcon(null);
        jTextField_Author.setText("");
        jLabel_ImagePhoto.setText("");

    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sActionPerformed
      Authors_list_Form1 form = new Authors_list_Form1();
        form.setEditBookForm(this);
        form.setVisible(true);
    }//GEN-LAST:event_jButton_sActionPerformed

    private void jComboBox_GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_GenreActionPerformed

    try {
        String selected = jComboBox_Genre.getSelectedItem().toString();

        if(genreMap.containsKey(selected))
        {
            int genreId = genreMap.get(selected);
            jLabel1_Genre_ID.setText(String.valueOf(genreId));
        }
        else
        {
            jLabel1_Genre_ID.setText("0");
        }

    } catch(Exception ex) {
        System.err.println("Genre error: " + ex.getMessage());
    }

    }//GEN-LAST:event_jComboBox_GenreActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:

        // close windo
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
                                         

    System.out.println("EDIT BUTTON CLICKED");

    Library_Domain.Book book = new Library_Domain.Book();

    int id = Integer.parseInt(jTextField_ID.getText());
    String isbn = jTextField_ISBN.getText();

    System.out.println("verif = " + verif());

    // 🔴 تحقق من الحقول
    if(!verif())
    {
        JOptionPane.showMessageDialog(null,
            "ISBN, Name, Author and Genre are Empty",
            "Empty Data",
            0);
        return;
    }

    try {

        System.out.println("ID = " + id);
        System.out.println("imagePath = " + imagePath);

        // 🔴 ISBN check الصحيح (يستثني نفس الكتاب)
        if(book.isISBNexists(isbn) && book.isbnExistsForOtherBook(isbn, id))
        {
            JOptionPane.showMessageDialog(null,
                "The ISBN already exists",
                "Wrong ISBN",
                0);
            return;
        }

        String name = jTextField_Name.getText();
        String publisher = jTextField_Publisher.getText();
        String description = jTextArea1_Description.getText();

        Integer author_id = Integer.parseInt(jLabel1_Author_ID.getText());
        Integer genre_id = Integer.parseInt(jLabel1_Genre_ID.getText());
        Integer quantity = Integer.parseInt(jSpinner_Quantity.getValue().toString());
        double price = Double.parseDouble(jTextField_Price_.getText());

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date_revived = dateFormat.format(jCalendarComboBox_Date.getDate());

        byte[] img = null;

        if(imagePath != null && !imagePath.trim().isEmpty())
        {
            Path path = Paths.get(imagePath);
            img = Files.readAllBytes(path);
        }

        book.editBook(id, name, author_id, genre_id, quantity,
                publisher, date_revived, price, description, img);

    }
    catch(IOException ex)
    {
        JOptionPane.showMessageDialog(null,
            "Make sure add cover Image : " + ex.getMessage());
    }
    catch(NumberFormatException ex)
    {
        JOptionPane.showMessageDialog(null,
            "You entered wrong data field : " + ex.getMessage());
    }
    catch(NullPointerException ex)
    {
        JOptionPane.showMessageDialog(null,
            "You need to select Date  : " + ex.getMessage());
    }

    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_AddBookCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddBookCoverActionPerformed

        String path = func.selectImage();
        jLabel_ImagePhoto.setText(path);
        // imagePath = path;
        func.displayImage(140, 150, null,path, jLabel_image_);
        imagePath = path;

    }//GEN-LAST:event_jButton_AddBookCoverActionPerformed

    private void jLabel_image_AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel_image_AncestorAdded

    }//GEN-LAST:event_jLabel_image_AncestorAdded

    private void jTextField_PublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PublisherActionPerformed

    private void jTextField_Price_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Price_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Price_ActionPerformed

    private void jTextField_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ISBNActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AuthorActionPerformed
              displayAuthorData(WIDTH, authors.getFirstName()+authors.getLastName());
    }//GEN-LAST:event_jTextField_AuthorActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //close form
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton_Search_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Search_ActionPerformed
    String idText = jTextField_ID.getText().trim();
    String isbn = jTextField_ISBN.getText().trim();

    Library_Domain.Book selectedBook = null;

    if(!idText.isEmpty())
    {
        selectedBook = book.searchBookByID(Integer.parseInt(idText));
    }
    else if(!isbn.isEmpty())
    {
        selectedBook = book.searchBookByISBN(isbn);
    }
    else
    {
        JOptionPane.showMessageDialog(
                null,
                "Enter Book ID or ISBN",
                "Search",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if(selectedBook != null)
    {
        jTextField_ID.setText(String.valueOf(selectedBook.getId()));
        jTextField_ISBN.setText(selectedBook.getIsbn());
        jTextField_Name.setText(selectedBook.getName());
        jTextField_Publisher.setText(selectedBook.getPublisher());
        jTextField_Price_.setText(String.valueOf(selectedBook.getPrice()));
        jSpinner_Quantity.setValue(selectedBook.getQuantity());
        jTextArea1_Description.setText(selectedBook.getDescription());
        java.util.Date date = null;
         try {
        date = new SimpleDateFormat("yyyy-MM-dd").parse(selectedBook.getDate_revived());
        } catch (Exception e) {
             e.printStackTrace();
                     }

         jCalendarComboBox_Date.setDate(date);
        jLabel1_Author_ID.setText(String.valueOf(selectedBook.getAuthor_id()));
        // author name
        String fullName = (authors.getAuthorsByID(selectedBook.getAuthor_id())).getFirstName()+" "+
         (authors.getAuthorsByID(selectedBook.getAuthor_id())).getLastName();
        jTextField_Author.setText(fullName);
        jLabel1_Genre_ID.setText(String.valueOf(selectedBook.getGenre_id()));
         for(Map.Entry<String,Integer> entry : genreMap.entrySet()){
              if(Objects.equals(selectedBook.getGenre_id(), entry.getValue())){
                 jComboBox_Genre.setSelectedItem(entry.getKey());
                    break;
                         }
                     }
          byte[] image = selectedBook.getCover();
                if (image != null && image.length > 0) {
                    func.displayImage(140, 145, image, "", jLabel_image_);
                } else {
                    jLabel_image_.setIcon(null);
                }
    }
    else
    {
        JOptionPane.showMessageDialog(
                null,
                "Book Not Found",
                "Search",
                JOptionPane.INFORMATION_MESSAGE
        );

        jTextField_Name.setText("");
        jTextField_Publisher.setText("");
        jTextField_Price_.setText("");
    }

        
        
    }//GEN-LAST:event_jButton_Search_ActionPerformed
      //===========================================================
  
      //=========================================================================
    public void displayAuthorData(int id , String fullName){
    jTextField_Author.setText(fullName);
    jLabel1_Author_ID.setText(String.valueOf(id));
    selectedAuthorId = id;
    }
    //=======================================================================
private boolean verif() {

    if(jTextField_ISBN.getText().trim().isEmpty()
    || jTextField_Name.getText().trim().isEmpty()
    || jLabel1_Author_ID.getText().trim().isEmpty()
    || jLabel1_Genre_ID.getText().trim().isEmpty())
    {
        return false;
    }

    return true;
}
 //==========================================================================
 
public void fillJcocomboboxWhidthGeneres()
    {
    for(String genreName : genreMap.keySet())
    {
    jComboBox_Genre.addItem(genreName);
    }
    
    }      
// create function to populate the table with Author
  public void populatJtablewithMember(String query) {
    try {
        // جلب قائمة الأعضاء من قاعدة البيانات داخل الـ try لحمايتها
        ArrayList<Library_Domain.Member> membersList = member.membersList(query);
        
        // أعمدة الجدول
        String[] colNames = {"ID", "F-NAME", "L-NAME", "PHONE", "EMAIL", "GENDER"};
        
        // الأسطر 
        Object[][] rows = new Object[membersList.size()][colNames.length];
        for (int i = 0; i < membersList.size(); i++) {
            rows[i][0] = membersList.get(i).getId();
            rows[i][1] = membersList.get(i).getFirstName();
            rows[i][2] = membersList.get(i).getLastName();
            rows[i][3] = membersList.get(i).getPhone();
            rows[i][4] = membersList.get(i).getEmail();
            rows[i][5] = membersList.get(i).getGender();
        }
        
       /* DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Members_.setModel(model); */
        
    } catch (java.sql.SQLException ex) {
        // في حال حدوث خطأ في قاعدة البيانات، يتم عرض رسالة تنبيه للمستخدم
        javax.swing.JOptionPane.showMessageDialog(null, "Error populating table: " + ex.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
  //==========================================================
 private void loadGenres()
{
    genreMap = new HashMap<>();

    Library_Domain.Genre g = new Library_Domain.Genre();

    genreMap = g.getGHashMap(); // 👈 مباشرة من الدالة الموجودة

    jComboBox_Genre.removeAllItems();

    for(String name : genreMap.keySet())
    {
        jComboBox_Genre.addItem(name);
    }
}
//=============================================================  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditBookForm1().setVisible(true));
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddBookCover;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Search_;
    private javax.swing.JButton jButton_s;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox_Date;
    private javax.swing.JComboBox<String> jComboBox_Genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private static javax.swing.JLabel jLabel1_Author_ID;
    private javax.swing.JLabel jLabel1_Genre_ID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_ImagePhoto;
    private javax.swing.JLabel jLabel_image_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_Image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_Quantity;
    private javax.swing.JTextArea jTextArea1_Description;
    private static javax.swing.JTextField jTextField_Author;
    private javax.swing.JTextField jTextField_Genre;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_ISBN;
    private javax.swing.JTextField jTextField_Id1;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Price_;
    private javax.swing.JTextField jTextField_Publisher;
    private javax.swing.JTextField jTextField_Quantity;
    private javax.swing.JTextField jTextField_recived_data;
    // End of variables declaration//GEN-END:variables


}
