/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Library_Presentation;

import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author LCS
 */
public class IssueBookForm1 extends javax.swing.JFrame {
    Library_Domain.Member member = new Library_Domain.Member();
    Library_Business.Function_Class func= new Library_Business.Function_Class();
    Library_Domain.Book book= new Library_Domain.Book();
   Library_Business.Issue_Book issue_Book= new Library_Business.Issue_Book();
    /**
     * Creates new form Member_List_info
     */
    public IssueBookForm1() {
          initComponents();
        // center form
        this.setLocationRelativeTo(null);
        
        // add borderto the panel Header                                      
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 5, 3, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
        try {
         java.net.URL imaUrl = getClass().getResource("/My_Images/BookDate.png");
             if (imaUrl != null) {
        String cleanPath = java.nio.file.Paths.get(imaUrl.toURI()).toFile().getAbsolutePath();
        
        func.displayImage(90, 60, null, cleanPath,  jLabel1);
    }
         } catch (Exception e) {
               e.printStackTrace();
                   }
        // fillJcocomboboxWhidthGeneres();
         //populate Jcombobox genres
      
        
    }
    /**
     * Creates new form IssueBookForm1
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_searchBook = new javax.swing.JButton();
        jLabel_BookName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_FullName = new javax.swing.JLabel();
        jButton_searchMember = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelAlvilable = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCalendarComboBox_issueDate = new de.wannawork.jcalendar.JCalendarComboBox();
        jCalendarComboBox_returnDate = new de.wannawork.jcalendar.JCalendarComboBox();
        jButton_Issue_ = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jSpinner_MemberID = new javax.swing.JSpinner();
        jSpinner_BookID = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_note = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setBackground(new java.awt.Color(1, 152, 117));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Issue Book");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(86, 80));
        jLabel2.setMinimumSize(new java.awt.Dimension(86, 80));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setText("Enter Book ID:");

        jButton_searchBook.setText("Search Book");
        jButton_searchBook.addActionListener(this::jButton_searchBookActionPerformed);

        jLabel_BookName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel_BookName.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_BookName.setText("Book Name");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel5.setText("Enter Member ID:");

        jLabel_FullName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel_FullName.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_FullName.setText("Member full Name");

        jButton_searchMember.setText("Search Member");
        jButton_searchMember.addActionListener(this::jButton_searchMemberActionPerformed);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel10.setText("Is This Book Alvilable :");

        jLabelAlvilable.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelAlvilable.setForeground(new java.awt.Color(51, 51, 255));
        jLabelAlvilable.setText("Yes-or-No");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel6.setText("Issue Date :");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel11.setText("Return Date :");

        jButton_Issue_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Issue_.setText("Issue");
        jButton_Issue_.addActionListener(this::jButton_Issue_ActionPerformed);

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(this::jButton_CancelActionPerformed);

        jSpinner_BookID.addChangeListener(this::jSpinner_BookIDStateChanged);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setText("Return Date :");

        jTextArea_note.setColumns(20);
        jTextArea_note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_note);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAlvilable, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendarComboBox_issueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendarComboBox_returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSpinner_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_searchMember))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_BookName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSpinner_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_searchBook)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jButton_Issue_, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_searchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel_BookName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_searchMember, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlvilable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendarComboBox_issueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendarComboBox_returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Issue_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //close form
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton_searchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchBookActionPerformed
       // search book & Display Book info & check if this book is available or not
        int book_Id = (int)jSpinner_BookID.getValue();
        try {
            
            //get book by ID
            Library_Domain.Book SelectBook = book.getBookByID(book_Id);
            //display Book name/Title
            if(SelectBook != null){
            jLabel_BookName.setText(SelectBook.getName());
            }else{    // if book ID not exist
            JOptionPane.showMessageDialog(null, "ID not exist","wrong",0);
            } 
        } catch (SQLException ex) {
           
             System.getLogger(IssueBookForm1.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
      
             }
    }//GEN-LAST:event_jButton_searchBookActionPerformed

    private void jButton_searchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchMemberActionPerformed
        // search member & Display member info 
        int member_Id = (int)jSpinner_MemberID.getValue();
        try {
             //get book by ID
            Library_Domain.Member SelectMember = member.getMemberByID(member_Id);
            //display Book name/Title
            if(SelectMember != null){
            jLabel_FullName.setText(SelectMember.getFirstName()+" "+ SelectMember.getLastName());
            }else{    // if book ID not exist
            JOptionPane.showMessageDialog(null, "ID not exist","wrong",0);
            } 
        } catch (SQLException ex) {
           
             System.getLogger(IssueBookForm1.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
      
             }
    }//GEN-LAST:event_jButton_searchMemberActionPerformed

    private void jButton_Issue_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Issue_ActionPerformed
                                                
    int _book_id = (int) jSpinner_BookID.getValue();
    int _member_id = (int) jSpinner_MemberID.getValue();
    String _note = jTextArea_note.getText();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    // 1. التحقق المبدئي من أن الأرقام ليست أصفاراً أو سالبة
    if (_book_id <= 0 || _member_id <= 0) {
        JOptionPane.showMessageDialog(null, "Enter correct Book ID and Member ID!", "wrong", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    
    // 2. التحقق من وجود العضو فعلياً في قاعدة البيانات
    if (!issue_Book.checkMemberExists(_member_id)) {
        JOptionPane.showMessageDialog(null, "This Member ID does not exist in the database!", "Member Not Found", JOptionPane.ERROR_MESSAGE);
        return; // يوقف التنفيذ تماماً ولا يكمل
    }
    
    // 3. الفحص الصارم لإتاحة الكتاب (تأكدي من مطابقة اسم الدالة المصلحة في الكلاس)
    if (issue_Book.checkBookAvailability(_book_id)) {
        jLabelAlvilable.setText("Yes");
        jLabelAlvilable.setForeground(java.awt.Color.GREEN);
    } else {
        jLabelAlvilable.setText("No"); 
        jLabelAlvilable.setForeground(java.awt.Color.RED);
        JOptionPane.showMessageDialog(null, "This book is not available or out of stock!", "Unavailable", JOptionPane.WARNING_MESSAGE);
        return; // يوقف التنفيذ هنا تماماً ولا يسمح بالتسجيل
    }
    
    // 4. التحقق من وجود التواريخ
    if (jCalendarComboBox_issueDate.getDate() == null || jCalendarComboBox_returnDate.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Select the issue date and return date please!", "wrong", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        String _issue_date = dateFormat.format(jCalendarComboBox_issueDate.getDate());
        String _return_date = dateFormat.format(jCalendarComboBox_returnDate.getDate());
        
        java.util.Date parsedIssue = dateFormat.parse(_issue_date);
        java.util.Date parsedReturn = dateFormat.parse(_return_date);
        
        // 5. التحقق المنطقي من التواريخ (أن تاريخ الإرجاع بعد الإعارة)
        if (parsedReturn.before(parsedIssue) || parsedReturn.equals(parsedIssue)) {
            JOptionPane.showMessageDialog(null, "The return date must be after the issued date!", "wrong!", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        // الإضافة الفعلية بعد تخطي كل شروط الحماية بنجاح
        issue_Book.addIssue(_book_id, _member_id, "issued", _issue_date, _return_date, _note);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Not issue: " + e.getMessage(), "wrong", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_jButton_Issue_ActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:

        // close windo
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jSpinner_BookIDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_BookIDStateChanged
        // TODO add your handling code here:                                       
    int _book_id = (int) jSpinner_BookID.getValue();
    
    // أولاً نتحقق لو الرقم صفر أو سالب عشان ما يضربش خطأ في الداتابيز
    if (_book_id <= 0) {
        jLabelAlvilable.setText("No");
        jLabelAlvilable.setForeground(java.awt.Color.RED);
        return; // يوقف هنا
    }
    
    // استدعاء دالة الفحص بعد التعديلات الأخيرة التي أجريناها
    if (issue_Book.checkBookAvailability(_book_id))
            {
        jLabelAlvilable.setText("Yes");
        jLabelAlvilable.setForeground(java.awt.Color.GREEN); // اللون أخضر
    } else {
        jLabelAlvilable.setText("No");
        jLabelAlvilable.setForeground(java.awt.Color.RED); // اللون أحمر
        JOptionPane.showMessageDialog(null, "this book not available or out of stock","Unavailable",JOptionPane.WARNING_MESSAGE);
        return;
    }
    }//GEN-LAST:event_jSpinner_BookIDStateChanged
   //======================================================================== 
  public void displayAuthorData(int id, String fullName) {

}
    //=======================================================================
private boolean verif() {
return true;
}
 //==========================================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
         //   logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueBookForm1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Issue_;
    private javax.swing.JButton jButton_searchBook;
    private javax.swing.JButton jButton_searchMember;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox_issueDate;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox_returnDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAlvilable;
    private javax.swing.JLabel jLabel_BookName;
    private javax.swing.JLabel jLabel_FullName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_BookID;
    private javax.swing.JSpinner jSpinner_MemberID;
    private javax.swing.JTextArea jTextArea_note;
    // End of variables declaration//GEN-END:variables
}
