/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Library_Presentation;
import Library_Data.DB;
import Library_Domain.Member;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omayma
 */
  
public class Member_List_info extends javax.swing.JFrame {
    Library_Domain.Member member = new Library_Domain.Member();
     Library_Business.Function_Class func= new Library_Business.Function_Class();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Member_List_info.class.getName());

    /**
     * Creates new form Member_List_info
     */
    public Member_List_info() {
          initComponents();
        // center form
        this.setLocationRelativeTo(null);
        
        // add borderto the panel Header                                      
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 5, 3, new Color(1,152,117));
        jPanel1.setBorder(panelHeaderBorder);
         try {
         java.net.URL imaUrl = getClass().getResource("/My_Images/Add_members.png");
             if (imaUrl != null) {
        // هذا السطر ينظف المسار من أي تشفير أو رموز زائدة لتقرأه الدالة بسلام
        String cleanPath = java.nio.file.Paths.get(imaUrl.toURI()).toFile().getAbsolutePath();
        
        func.displayImage(90, 60, null, cleanPath,  jLabel1);
    }
         } catch (Exception e) {
               e.printStackTrace();
                   }
          Library_Business.BaseUI_Service buis = new Library_Business.BaseUI_Service();
        // customize table
        buis.customizeTable(jTable_Members_, new Color(1,152,117), Color.white);

       populatJtablewithMember("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2_Image = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Members_ = new javax.swing.JTable();
        jButton_search = new javax.swing.JButton();
        jLabel_fullName = new javax.swing.JLabel();
        jLabel_phon = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_gender = new javax.swing.JLabel();
        jLabel_image1 = new javax.swing.JLabel();
        jButton_search1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2_ImageLayout = new javax.swing.GroupLayout(jPanel2_Image);
        jPanel2_Image.setLayout(jPanel2_ImageLayout);
        jPanel2_ImageLayout.setHorizontalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2_ImageLayout.setVerticalGroup(
            jPanel2_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(1, 152, 117));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("قائمة بالاعضاء");
        jLabel1.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setText("ادخل اسم العضو للبحث");

        jTextField_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_search.addActionListener(this::jTextField_searchActionPerformed);

        jTable_Members_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Members_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Members_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Members_);

        jButton_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_search.setText("بحث");
        jButton_search.addActionListener(this::jButton_searchActionPerformed);

        jLabel_fullName.setText("الاسم يالكامل ");

        jLabel_phon.setText("الهاتف");

        jLabel_Email.setText("البريد");

        jLabel_gender.setText("الجنس");

        jLabel_image1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_image1.setOpaque(true);

        jButton_search1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_search1.setText("تقرير");
        jButton_search1.addActionListener(this::jButton_search1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_phon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_image1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(jLabel_fullName, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_search))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_fullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_phon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_gender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButton_search1)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //close form
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    
    // create function to populate the table with Author
  public void populatJtablewithMember(String query) {
    try {
        // جلب قائمة الأعضاء من قاعدة البيانات داخل الـ try لحمايتها
        ArrayList<Library_Domain.Member> membersList = member.membersList(query);
        
        // أعمدة الجدول
        String[] colNames = { "الجنس", "البريد", "الهاتف", "اللقب", "الاسم","ID"};
        
        // الأسطر 
        Object[][] rows = new Object[membersList.size()][colNames.length];
        for (int i = 0; i < membersList.size(); i++) {
            rows[i][5] = membersList.get(i).getId();
            rows[i][4] = membersList.get(i).getFirstName();
            rows[i][3] = membersList.get(i).getLastName();
            rows[i][2] = membersList.get(i).getPhone();
            rows[i][1] = membersList.get(i).getEmail();
            rows[i][0] = membersList.get(i).getGender();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Members_.setModel(model);
        
    } catch (java.sql.SQLException ex) {
        // في حال حدوث خطأ في قاعدة البيانات، يتم عرض رسالة تنبيه للمستخدم
        javax.swing.JOptionPane.showMessageDialog(null, "Error populating table: " + ex.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    
    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:
         // search & display data in table 
        String value = jTextField_search.getText();
        String query ="SELECT * FROM `members` WHERE `firstName` LIKE '%" + value +"%' OR `lastName` LIKE '%" + value + "%'";
        populatJtablewithMember(query); 
    }//GEN-LAST:event_jTextField_searchActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        // search & display data in table 
        String value = jTextField_search.getText();
        String query ="SELECT * FROM `members` WHERE `firstName` LIKE '%" + value +"%' OR `lastName` LIKE '%" + value + "%'";
        populatJtablewithMember(query);
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jTable_Members_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Members_MouseClicked
    try {
        // 1. استدعاء ملف التصميم المحدث jrxml بدلاً من jasper
        java.io.InputStream reportStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("MEMBER_REPORT.jrxml");
        if (reportStream == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "لم يتم العثور على ملف تصميم التقرير (jrxml)!");
            return;
        }

        // 2. عمل Compile للملف برمجياً ليأخذ آخر التعديلات فوراً
        net.sf.jasperreports.engine.JasperReport jasperReport = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);

        // 3. الباراميترز
        java.util.HashMap<String, Object> parameters = new java.util.HashMap<>();
        
        // 4. تعبئة التقرير بالبيانات باستخدام الـ jasperReport الجديد
        net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasperReport, parameters, DB.getConnection());

        // 5. عرض التقرير
        net.sf.jasperreports.view.JasperViewer viewer = new net.sf.jasperreports.view.JasperViewer(jasperPrint, false);
        viewer.setTitle("قائمة الاعضاء");
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "خطأ أثناء عرض التقرير: " + e.getMessage());
    }

    }//GEN-LAST:event_jTable_Members_MouseClicked

    private void jButton_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search1ActionPerformed
    try {
        // 1. طباعة مسار المجلد الحالي للمشروع لتعرفي أين يبحث الجافا
        String currentDir = new java.io.File(".").getAbsolutePath();
        System.out.println("المسار الحالي للمشروع هو: " + currentDir);
        
        // 2. محاولة القراءة من المجلد الرئيسي للمشروع مباشرة كحل بديل ومضمون
        java.io.File reportFile = new java.io.File("MEMBER_REPORT.jrxml");
        
        // إذا لم يجده في المجلد الرئيسي، نجرب مجلد الـ src
        if (!reportFile.exists()) {
            reportFile = new java.io.File("src/main/resources/MEMBER_REPORT.jrxml");
        }
        
        // إذا لم يجده أيضاً، سنظهر رسالة بالمسار الذي بحث فيه لنتأكد
        if (!reportFile.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "لم يجد الملف في المسار: \n" + reportFile.getAbsolutePath());
            return;
        }

        // 3. قراءة الملف بعدما عثرنا عليه بالتأكيد
        java.io.InputStream reportStream = new java.io.FileInputStream(reportFile);

        // 4. عمل Compile للملف برمجياً
        net.sf.jasperreports.engine.JasperReport jasperReport = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);

        // 5. الباراميترز والـ Fill
        java.util.HashMap<String, Object> parameters = new java.util.HashMap<>();
        net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasperReport, parameters, DB.getConnection());

        // 6. عرض التقرير
        net.sf.jasperreports.view.JasperViewer viewer = new net.sf.jasperreports.view.JasperViewer(jasperPrint, false);
        viewer.setTitle("قائمة الاعضاء");
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "خطأ أثناء عرض التقرير: " + e.getMessage());
    
       
}
    }//GEN-LAST:event_jButton_search1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Member_List_info().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_search1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_fullName;
    private javax.swing.JLabel jLabel_gender;
    private javax.swing.JLabel jLabel_image1;
    private javax.swing.JLabel jLabel_phon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_Image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Members_;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
